### ISSUE TITLE
User Guide down

### ISSUE THREAD

**Issue by agucova** [cwatson/brainGraph#1]
Is the any alternative link for the user link? Dropbox seems to no longer have the file.

**Comment by cwatson** [comment]
Yes, you can find it here: https://www.dropbox.com/s/im9ej66veimk3hl/brainGraph_UserGuide.pdf?dl=0
This link might get broken, but I am working on a more permanent solution (via Github Pages). This will happen at the same time I push the v2.0.0 updates to Github
