### ISSUE TITLE
Remapping coordinates into DK

### ISSUE THREAD

**Issue by bgunasekera** [cwatson/brainGraph#27]
Hi,

I am unsure if this is an appropriate ask of brainGraph.

Nevertheless, I have a list of coordinates I would like to parcellate across the DK atlas. Is this possible using brainGraph? 

Best wishes,
Brandon

**Comment by cwatson** [comment]
Sorry, I'm not sure what you're interested in, exactly, but this seems like it would have to be done outside of _brainGraph_. Perhaps see if _FreeSurfer_ can achieve what you'd like.
