### ISSUE TITLE
Problem with "create_mats"

### ISSUE THREAD

**Issue by MarianaV52** [cwatson/brainGraph#30]
Hi, thank you for developing this package! I want to create an array with all my ".mat" files but it appears this issue: 

> DCF_mats<- list(path= 'C:/Users/maval/OneDrive/Data_dsi/Primer_analisis_preliminar_dsi/DCF_todaslasmat')
> DCF_array<- create_mats(DCF_mats, modality = "dti", algo = "deterministic")
Error in create_mats(DCF_mats, modality = "dti", algo = "deterministic") : 
  length(A.files) == nz is not TRUE

**Comment by cwatson** [comment]
Hello, that error means that the file list (i.e., `A.files`) is either incorrectly specified, or you should explicitly provide a value for the `inds` function argument. Please read through the **User Guide Chapter 7** in particular.
