### ISSUE TITLE
Using brainGraph with ecological data.

### ISSUE THREAD

**Issue by RGTake** [cwatson/brainGraph#7]
Hi Chris,

I am interested in using brainGraph package to access vertex roles in some igraph network I am working. My problem is I don't know what this {memb}{A numeric vector of membership indices of each vertex} means. Can I extract it from my igraph networks? Bear with me because I am a noobie at this. Thanks in advance.

Rodrigo

**Comment by RGTake** [comment]
Thanks Chris. 

Yes, I refer to part_coeff, or within_module_deg_z_score. 

Ok, so it must separate vertices into different groups. Does this groups enter the calculations? Because I can only think I can use species as a "group". My vertices represent different microbial species found in my samples. I could create a vector that would map to it but it would be very random. 

Would it work?

**Comment by cwatson** [comment]
The typical/classic usage would be to use the output of a community detection algorithm for different groups. Specifically, the `membership` element of the algorithm's results. You can read the references specified in the functions' manual page for background information, and you can check out the code in `set_brainGraph_attrs` for how I call the functions you are asking about.

Let me know if you have other questions.
Chris

**Comment by cwatson** [comment]
Hi @RGTake , I will close this issue; however, if I haven't sufficiently answered your questions you may re-open it.
